### ISSUE TITLE
No tor in Heroku

### ISSUE THREAD

**Issue by jpchen** [apg/heroku-tor-buildpack#1]
Following the directions to get the hidden variables, tor is not installed on the dyno and I can't find a way to install it since Heroku does not allow root access to install software.
~ $ tor -f tmptorrc
bash: tor: command not found
~ $ sudo apt-get install tor
bash: sudo: command not found
~ $  apt-get install tor
W: Not using locking for read only lock file /var/lib/dpkg/lock
E: Unable to write to /var/cache/apt/
E: The package lists or status file could not be parsed or opened.

Please assist!

**Comment by apg** [comment]
What is the output of the build when you do a git push?

**Comment by jpchen** [comment]
Let me know if you need the full output, but it says installed tor successfully.

...
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/bin'
remote:   /usr/bin/install -c src/or/tor src/tools/tor-resolve src/tools/tor-gencert '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/bin'
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/bin'
remote:  /usr/bin/install -c contrib/client-tools/torify '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/bin'
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/etc/tor'
remote:  /usr/bin/install -c -m 644 src/config/torrc.sample '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/etc/tor'
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/doc/tor'
remote:  /usr/bin/install -c -m 644 doc/tor.html doc/tor-gencert.html doc/tor-resolve.html doc/torify.html '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/doc/tor'
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/man/man1'
remote:  /usr/bin/install -c -m 644 doc/tor.1 doc/tor-gencert.1 doc/tor-resolve.1 doc/torify.1 '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/man/man1'
remote:  /bin/mkdir -p '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/tor'
remote:  /usr/bin/install -c -m 644 src/config/geoip src/config/geoip6 '/tmp/build_b6d010cdda1a74b1f9c3e42e83f01b5d/share/tor'
remote: make[1]: Leaving directory `/app/tmp/buildpacks/9131f80a68f0f9ebeedf10e129f9181691f1b5262d706427f9242798752e6e61821b4b1ae82d5d9b0263fdc3ce5b3c7d7f5dcfbdf72d75d0ca42b825a59badfa/tor-0.2.7.6'
remote:       **Installed Tor successfully**
remote: -----> Discovering process types
remote:        Procfile declares types -> worker
remote:
remote: -----> Compressing...
remote:        Done: 76.4M
remote: -----> Launching...
remote:        Released v8
remote:        https://guarded-thicket-54590.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/guarded-thicket-54590.git
   811ec41..4a96071  master -> master

**Comment by apg** [comment]
I have a little app, [hidden-polls](https://github.com/apg/hidden-polls), that was the test app for this buildpack. If I `heroku run -a tor-hidden-polls bash`

``` bash
~ $ ls -R
.:
Godeps  LICENSE  Procfile  Procfile.dev  README.md  bin  etc  main.go  schema  share  vendor

...SNIP...

./bin:
hidden-polls  hide  tor  tor-gencert  tor-resolve  torify

./etc:
tor

./etc/tor:
torrc.sample

...SNIP...

./share:
doc  man  tor

./share/doc:
tor

./share/doc/tor:
tor-gencert.html  tor-resolve.html  tor.html  torify.html

...SNIP...

./share/man/man1:
tor-gencert.1  tor-resolve.1  tor.1  torify.1

./share/tor:
geoip  geoip6

...SNIP...

```

The `tor` executable should just be at `/app/bin/tor`. Maybe the latest versions of tor make different assumptions? I'll have to take a closer look, but won't be able to until tomorrow, most likely.

**Comment by spencerthayer** [comment]
What happened with this?

**Comment by apg** [comment]
@spencerthayer I could never reproduce and the the OP never responded. Going to close since it's been close to a year.

**Comment by vlad13242** [comment]
q
