### ISSUE TITLE
Can not get Variables, I try to run HIDDEN PRIVATEKEY and HIDDEN DOT ONION, but there is no return value

### ISSUE THREAD

**Issue by ghost** [apg/heroku-tor-buildpack#2]
Can not get Variables, I try to run HIDDEN PRIVATEKEY and HIDDEN DOT ONION, but there is no return value

**Comment by apg** [comment]
As I mentioned in apg/hidden-polls#1, you can obtain these after you do a git push.

**Comment by ghost** [comment]
I have successfully git push,
But were unable to obtain these variables

**Comment by apg** [comment]
You don't need to get these variables from a Heroku app. They are the same values you get when you run any hidden service. If you have tor setup on your machine, expose a hidden service, find the values that get created and use those.
